# Generated by Django 5.0.7 on 2024-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaDestinoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teatro', models.CharField(max_length=100)),
                ('avenida', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar1', models.CharField(max_length=100)),
                ('lugar2', models.CharField(max_length=100)),
                ('lugar3', models.CharField(max_length=100)),
                ('lugar4', models.CharField(max_length=100)),
                ('lugar5', models.CharField(max_length=100)),
                ('lugar6', models.CharField(max_length=100)),
                ('motivo1', models.CharField(max_length=100)),
                ('motivo2', models.CharField(max_length=100)),
                ('motivo3', models.CharField(max_length=100)),
                ('motivo4', models.CharField(max_length=100)),
                ('motivo5', models.CharField(max_length=100)),
                ('motivo6', models.CharField(max_length=100)),
                ('orden1', models.IntegerField()),
                ('orden2', models.IntegerField()),
                ('orden3', models.IntegerField()),
                ('orden4', models.IntegerField()),
                ('orden5', models.IntegerField()),
                ('orden6', models.IntegerField()),
            ],
        ),
    ]
